services:
  redis:
    image: redis:8.2.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  
  postgres:
    image: postgres:16
    container_name: swytch-postgres    
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  redisdata: