services:
  redis:
    image: redis:8.2.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  
  postgres:
    image: postgres:16
    container_name: swytch-postgres    
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: swytch-minio
    ports:
      - "9000:9000"       # S3 API
      - "9001:9001"       # MinIO Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data   

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol (for apps/workers)
      - "15672:15672" # HTTP management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 

volumes:
  redisdata:
  pgdata:
  minio_data:
  rabbitmq_data: