// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: job.sql

package sql

import (
	"context"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs DEFAULT
VALUES
RETURNING id, created_at, updated_at
`

func (q *Queries) CreateJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRow(ctx, createJob)
	var i Job
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, created_at, updated_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id int32) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
